server:
  port: 80

---
spring:
  profiles: development

logging:
  level:
    root: DEBUG

---
spring:
  profiles: production

logging:
  path: /logs/
  file: app.log
  level:
    root: WARN

---
spring:
  profiles: test

server:
  ssl:
    enabled: false

logging:
  level:
    root: DEBUG