application:
 datasource:
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true
  useLocalSessionState: true
  rewriteBatchedStatements: true
  cacheResultSetMetadata: true
  cacheServerConfiguration: true
  elideSetAutoCommits: true
  maintainTimeStats: false

server:
 port: 80

spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: password
  hikari:
   maximum-pool-size: 20

---
spring:
 profiles: development
 datasource:
  url: jdbc:mysql://localhost:3306/genreisromance?serverTimezone=Asia/Seoul&userUnicode=true&characterEncoding=utf-8

logging:
 level:
  root: DEBUG
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.zaxxer.hikari: TRACE

---
spring:
 profiles: production

logging:
 path: /logs/
 file: app.log
 level:
  root: WARN

---
spring:
 profiles: test
 datasource:
  url: jdbc:mysql://localhost:3306/genreisromance?serverTimezone=Asia/Seoul&userUnicode=true&characterEncoding=utf-8

server:
 ssl:
  enabled: false

logging:
 level:
  root: DEBUG