app:
 security:
  jwt:
   secret-key: 5867a8374e7c0f6284b177b48faf89e1c79d72d8  # github에 커밋되어 있음
   token-validity-in-seconds: 86400 # 24 hour
   token-validity-in-seconds-for-remember-me: 2592000

 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/genreisromance?serverTimezone=Asia/Seoul&userUnicode=true&characterEncoding=utf-8
  username: root
  password: password
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true
  useLocalSessionState: true
  rewriteBatchedStatements: true
  cacheResultSetMetadata: true
  cacheServerConfiguration: true
  elideSetAutoCommits: true
  maintainTimeStats: false

  hikari:
   maximum-pool-size: 20

server:
 port: 5959

spring:
 jpa:
  properties:
   hibernate:
    format_sql: true
    default_batch_fetch_size: 30
  hibernate:
   ddl-auto: create
  generate-ddl: true
  show-sql: true
  database: mysql

---
spring:
 profiles: development

logging:
 level:
  root: DEBUG
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.zaxxer.hikari: TRACE

---
spring:
 profiles: production
 jpa:
  hibernate:
   ddl-auto: update

logging:
 path: /logs/
 file: app.log
 level:
  root: WARN

---
spring:
 profiles: test

server:
 ssl:
  enabled: false

logging:
 level:
  root: DEBUG